package com.linkage.ftpdrudgery.db.fd.bean;

public class FdHisMonitorExp {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR_EXP.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String snId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR_EXP.MAP_KEY
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String mapKey;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR_EXP.MAP_VALUE
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String mapValue;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR_EXP.SN_ID
     *
     * @return the value of FD.FD_HIS_MONITOR_EXP.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getSnId() {
        return snId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR_EXP.SN_ID
     *
     * @param snId the value for FD.FD_HIS_MONITOR_EXP.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setSnId(String snId) {
        this.snId = snId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR_EXP.MAP_KEY
     *
     * @return the value of FD.FD_HIS_MONITOR_EXP.MAP_KEY
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getMapKey() {
        return mapKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR_EXP.MAP_KEY
     *
     * @param mapKey the value for FD.FD_HIS_MONITOR_EXP.MAP_KEY
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setMapKey(String mapKey) {
        this.mapKey = mapKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR_EXP.MAP_VALUE
     *
     * @return the value of FD.FD_HIS_MONITOR_EXP.MAP_VALUE
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getMapValue() {
        return mapValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR_EXP.MAP_VALUE
     *
     * @param mapValue the value for FD.FD_HIS_MONITOR_EXP.MAP_VALUE
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setMapValue(String mapValue) {
        this.mapValue = mapValue;
    }
}