package com.linkage.ftpdrudgery.db.fd.bean;

public class FdHisMonitorKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String snId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR.TASK_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String taskId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD.FD_HIS_MONITOR.TASK_NAME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String taskName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR.SN_ID
     *
     * @return the value of FD.FD_HIS_MONITOR.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
	
    private String selectKey;
    
    private String taskStatus;
    private String taskDate;
    
    public String getSnId() {
        return snId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR.SN_ID
     *
     * @param snId the value for FD.FD_HIS_MONITOR.SN_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setSnId(String snId) {
        this.snId = snId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR.TASK_ID
     *
     * @return the value of FD.FD_HIS_MONITOR.TASK_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR.TASK_ID
     *
     * @param taskId the value for FD.FD_HIS_MONITOR.TASK_ID
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD.FD_HIS_MONITOR.TASK_NAME
     *
     * @return the value of FD.FD_HIS_MONITOR.TASK_NAME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD.FD_HIS_MONITOR.TASK_NAME
     *
     * @param taskName the value for FD.FD_HIS_MONITOR.TASK_NAME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

	public void setSelectKey(String selectKey) {
		this.selectKey = selectKey;
	}

	public String getSelectKey() {
		return selectKey;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	public String getTaskStatus() {
		return taskStatus;
	}

	public void setTaskDate(String taskDate) {
		this.taskDate = taskDate;
	}

	public String getTaskDate() {
		return taskDate;
	}
}