package com.linkage.ftpdrudgery.db.fd.bean;

import java.util.Date;

public class FdHisMonitor extends FdHisMonitorKey{
	
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD_HIS_MONITOR.TASK_STATUS
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String taskStatus;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD_HIS_MONITOR.START_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private Date startTime;
    
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD_HIS_MONITOR.END_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private Date endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD_HIS_MONITOR.CAST_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private String castTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column FD_HIS_MONITOR.INSERT_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    private Date insertTime; 
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD_HIS_MONITOR.TASK_STATUS
     *
     * @return the value of FD_HIS_MONITOR.TASK_STATUS
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD_HIS_MONITOR.TASK_STATUS
     *
     * @param castTime the value for FD_HIS_MONITOR.TASK_STATUS
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
    }   
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD_HIS_MONITOR.START_TIME
     *
     * @return the value of FD_HIS_MONITOR.START_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD_HIS_MONITOR.START_TIME
     *
     * @param startTime the value for FD_HIS_MONITOR.START_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD_HIS_MONITOR.END_TIME
     *
     * @return the value of FD_HIS_MONITOR.END_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD_HIS_MONITOR.END_TIME
     *
     * @param endTime the value for FD_HIS_MONITOR.END_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD_HIS_MONITOR.CAST_TIME
     *
     * @return the value of FD_HIS_MONITOR.CAST_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public String getCastTime() {
        return castTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD_HIS_MONITOR.CAST_TIME
     *
     * @param castTime the value for FD_HIS_MONITOR.CAST_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setCastTime(String castTime) {
        this.castTime = castTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column FD_HIS_MONITOR.INSERT_TIME
     *
     * @return the value of FD_HIS_MONITOR.INSERT_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column FD_HIS_MONITOR.INSERT_TIME
     *
     * @param insertTime the value for FD_HIS_MONITOR.INSERT_TIME
     *
     * @abatorgenerated Mon Aug 29 10:11:06 CST 2011
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
    
}