package com.linkage.ftpdrudgery.db.ods.bean;

import java.util.Date;

public class OdsPubLog {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.ETL_DATA_CYCLE
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private String etlDataCycle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.SCHEMA_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private String schemaName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.TABLE_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private String tableName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.START_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private Date startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.END_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private Date endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.ODS_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private Short odsFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.DWD_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private Short dwdFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VGOP_ODS.ODS_PUB_LOG.DATA_CNT
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    private Integer dataCnt;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.ETL_DATA_CYCLE
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.ETL_DATA_CYCLE
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public String getEtlDataCycle() {
        return etlDataCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.ETL_DATA_CYCLE
     *
     * @param etlDataCycle the value for VGOP_ODS.ODS_PUB_LOG.ETL_DATA_CYCLE
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setEtlDataCycle(String etlDataCycle) {
        this.etlDataCycle = etlDataCycle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.SCHEMA_NAME
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.SCHEMA_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.SCHEMA_NAME
     *
     * @param schemaName the value for VGOP_ODS.ODS_PUB_LOG.SCHEMA_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.TABLE_NAME
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.TABLE_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.TABLE_NAME
     *
     * @param tableName the value for VGOP_ODS.ODS_PUB_LOG.TABLE_NAME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.START_TIME
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.START_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.START_TIME
     *
     * @param startTime the value for VGOP_ODS.ODS_PUB_LOG.START_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.END_TIME
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.END_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.END_TIME
     *
     * @param endTime the value for VGOP_ODS.ODS_PUB_LOG.END_TIME
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.ODS_FLAG
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.ODS_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public Short getOdsFlag() {
        return odsFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.ODS_FLAG
     *
     * @param odsFlag the value for VGOP_ODS.ODS_PUB_LOG.ODS_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setOdsFlag(Short odsFlag) {
        this.odsFlag = odsFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.DWD_FLAG
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.DWD_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public Short getDwdFlag() {
        return dwdFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.DWD_FLAG
     *
     * @param dwdFlag the value for VGOP_ODS.ODS_PUB_LOG.DWD_FLAG
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setDwdFlag(Short dwdFlag) {
        this.dwdFlag = dwdFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VGOP_ODS.ODS_PUB_LOG.DATA_CNT
     *
     * @return the value of VGOP_ODS.ODS_PUB_LOG.DATA_CNT
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public Integer getDataCnt() {
        return dataCnt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VGOP_ODS.ODS_PUB_LOG.DATA_CNT
     *
     * @param dataCnt the value for VGOP_ODS.ODS_PUB_LOG.DATA_CNT
     *
     * @abatorgenerated Fri Oct 14 10:42:10 CST 2011
     */
    public void setDataCnt(Integer dataCnt) {
        this.dataCnt = dataCnt;
    }
}